<form method="post" action="">
	<?php wp_nonce_field( "post_edit_restrictions_{$post_type}" ); ?>
	<table class='form-table'>
		<tr>
			<th scope='row'><label for="restrict_time"><?php _e( 'Time Limit', 'post-edit-restrictions' ); ?></label></th>
			<td><?php _e('Restrict post editing after', 'post-edit-restrictions'); ?>: 
				<input id="restrict_time" type="number" name="time" min="0" step="1" value="<?php esc_attr_e( $time ); ?>"> <?php _e('minutes', 'post-edit-restrictions'); ?>.
				<p class="description">
					<?php _e( 'Set it to zero to disallow editing entirely. ', 'post-edit-restrictions' ); ?><br/>
				</p>
			</td>
		</tr>
		<tr>
			<th scope='row'><?php _e( 'Roles', 'post-edit-restrictions' ); ?></th>
			<td>
				<?php foreach ( $roles as $id => $role ) : ?>
				<?php
					$id      = esc_attr( $id );
					$checked = isset( $settings['roles'][$id] ) ? ' checked="checked"' : ''; ?>
				<label for="role_<?php echo $id; ?>">
					<input id="role_<?php echo  $id; ?>" type="checkbox" name="roles[<?php echo  $id; ?>]"<?php echo $checked; ?>>
					<?php echo $role ?>
				</label><br/>
				<?php endforeach; ?>
				<p class="description">
					<?php _e( 'Select user roles to restrict post editing by a time limit.', 'post-edit-restrictions' ); ?><br/>
				</p>
			</td>
		</tr>
	</table>
	<p class="submit">
		<input id="submit" class="button button-primary" name="post_edit_restrict" value="Update Settings" type="submit">
	</p>
</form>
<p> 
<?php printf( __( 'This page is generated by the %s plugin.', 'post-edit-restrictions' ), '<a href="https://github.com/keesiemeijer/post-edit-restrictions">' . __('Post Edit Restrictions', 'post-edit-restrictions') . '</a>'); ?>
</p>
